### ISSUE TITLE
Help with script

### ISSUE THREAD

**Issue by Mayki07** [jorijnsmit/onlineChecker#12]
Please help. If I run the script from cmd directly in the directory, it works:

`pi@raspberrypi:~ $ cd /home/pi/domoticz/scripts/onlineChecker
pi@raspberrypi:~/domoticz/scripts/onlineChecker $ python online_checker.py
192.168.0.151 is online, but Domoticz already knew.`

If I run the command like this, it does not work:
`pi@raspberrypi:~ $ python /home/pi/domoticz/scripts/onlineChecker/online_checker.py
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/onlineChecker/online_checker.py", line 15, in <module>
    DOMO = CONFIG['DOMOTICZ']
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'DOMOTICZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/onlineChecker/online_checker.py", line 18, in <module>
    raise Exception('Config file is unreadable or incomplete.')
Exception: Config file is unreadable or incomplete.`

I don't know where the mistake may be. Automatic script execution also doesn't work for me. Can you help me?

**Comment by Mayki07** [comment]
This works:
`python /home/pi/domoticz/scripts/onlineChecker/online_checker.py /home/pi/domoticz/scripts/onlineChecker/config.ini`
